/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;

/**
 * Clase que proporcion la vista esqueleto
 * @author Juanra
 */
public class Esqueleto extends javax.swing.JFrame {

    /**
     * Creates new form Esqueleto
     */
    public Esqueleto() {
        initComponents();
        //setLocationRelativeTo(null);
        //getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        mBar = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        iProductos = new javax.swing.JMenuItem();
        iSalir = new javax.swing.JMenuItem();
        mInformes = new javax.swing.JMenu();
        iInformes = new javax.swing.JMenuItem();
        mAyuda = new javax.swing.JMenu();
        iAyuda = new javax.swing.JMenuItem();
        iInfo = new javax.swing.JMenuItem();
        MAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        mArchivo.setText("Archivo");

        iProductos.setText("Cursos");
        mArchivo.add(iProductos);

        iSalir.setText("Salir");
        iSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iSalirActionPerformed(evt);
            }
        });
        mArchivo.add(iSalir);

        mBar.add(mArchivo);

        mInformes.setText("Informes");

        iInformes.setText("Informes");
        iInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iInformesActionPerformed(evt);
            }
        });
        mInformes.add(iInformes);

        mBar.add(mInformes);

        mAyuda.setText("Ayuda");

        iAyuda.setText("Ayuda");
        mAyuda.add(iAyuda);

        iInfo.setText("Info");
        mAyuda.add(iInfo);

        MAyuda.setText("Mostrar Ayuda...");
        mAyuda.add(MAyuda);

        mBar.add(mAyuda);

        setJMenuBar(mBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel7)
                .addContainerGap(269, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(jLabel7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iSalirActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_iSalirActionPerformed

    private void iInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iInformesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iInformesActionPerformed

    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Esqueleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Esqueleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Esqueleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Esqueleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Esqueleto().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem MAyuda;
    public javax.swing.JMenuItem iAyuda;
    public javax.swing.JMenuItem iInfo;
    public javax.swing.JMenuItem iInformes;
    public javax.swing.JMenuItem iProductos;
    public javax.swing.JMenuItem iSalir;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JMenu mArchivo;
    public javax.swing.JMenu mAyuda;
    public javax.swing.JMenuBar mBar;
    public javax.swing.JMenu mInformes;
    // End of variables declaration//GEN-END:variables
}
